dashboard:
    resource: '@DashboardBundle/Resources/config/routing.yml'

api:
    resource: '@DeprovisionApiBundle/Resources/config/routing.yml'
    prefix: /api

dashboard_saml:
    resource: "@DashboardSamlBundle/Controller/"
    type:     annotation
    prefix:   /

openconext_monitor:
    resource: "@OpenConextMonitorBundle/Resources/config/routing.yml"
    prefix: /

lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix:   /translations
